export const LOAD_CLIENTS = "LOAD_CLIENTS";
export const LOAD_CLIENTS_SUCCESS = "LOAD_CLIENTS_SUCCESS";
export const LOAD_CLIENTS_FAILED = "LOAD_CLIENTS_FAILED";
export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT";

export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const LOAD_LOCATIONS_FAILED = "LOAD_LOCATIONS_FAILED";

export const LOAD_LOCATION_TIMESLOTS = "LOAD_LOCATION_TIMESLOTS";
export const LOAD_LOCATION_TIMESLOTS_SUCCESS =
  "LOAD_LOCATION_TIMESLOTS_SUCCESS";
export const LOAD_LOCATION_TIMESLOTS_FAILED = "LOAD_LOCATION_TIMESLOTS_FAILED";

export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";

export const LOAD_VACCINE_TYPES = "LOAD_VACCINE_TYPES";
export const LOAD_VACCINE_TYPES_SUCCESS = "LOAD_VACCINE_TYPES_SUCCESS";
export const LOAD_VACCINE_TYPES_FAILED = "LOAD_VACCINE_TYPES_FAILED";

export const LOAD_ZIP_AVAILABLE_CODES = "LOAD_ZIP_AVAILABLE_CODES";
export const LOAD_ZIP_AVAILABLE_CODES_SUCCESS =
  "LOAD_ZIP_AVAILABLE_CODES_SUCCESS";
export const LOAD_ZIP_AVAILABLE_CODES_FAILED =
  "LOAD_ZIP_AVAILABLE_CODES_FAILED";

export const SAVE_CLIENT_LOCATION = "SAVE_CLIENT_LOCATION";
export const SAVE_CLIENT_LOCATION_SUCCESS = "SAVE_CLIENT_LOCATION_SUCCESS";
export const SAVE_CLIENT_LOCATION_FAILED = "SAVE_CLIENT_LOCATION_FAILED";

export const SAVE_LOCATION_TIMESLOTS = "SAVE_LOCATION_TIMESLOTS";
export const SAVE_LOCATION_TIMESLOTS_SUCCESS =
  "SAVE_LOCATION_TIMESLOTS_SUCCESS";
export const SAVE_LOCATION_TIMESLOTS_FAILED = "SAVE_LOCATION_TIMESLOTS_FAILED";

export const INIT_ADD_CLIENT_LOCATION_FORM = "INIT_ADD_CLIENT_LOCATION_FORM";
export const INIT_EDIT_CLIENT_LOCATION_FORM = "INIT_EDIT_CLIENT_LOCATION_FORM";

export const TOGGLE_LOCATION_TIMESLOT_STATUS =
  "TOGGLE_LOCATION_TIMESLOT_STATUS";

export const DEACTIVATE_ALL_TIMESLOTS = "DEACTIVATE_ALL_TIMESLOTS";

export const ACTIVATE_ALL_TIMESLOTS = "ACTIVATE_ALL_TIMESLOTS";
export const UPDATE_LOCATION_TIMESLOTS_SUCCESS =
  "UPDATE_LOCATION_TIMESLOTS_SUCCESS";